---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list:
  - recipe[apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box
- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[php]
  attributes: {}

- name: source
  run_list:
  - recipe[php]
  attributes:
    php:
      install_method: source

- name: module-packages
  run_list:
  - recipe[php]
  - recipe[php::module_apc]
  - recipe[php::module_curl]
  - recipe[php::module_fpdf]
  - recipe[php::module_gd]
  - recipe[php::module_ldap]
  - recipe[php::module_memcache]
  - recipe[php::module_mysql]
  - recipe[php::module_pgsql]
  - recipe[php::module_sqlite3]
  attributes: {}
